before_install:
  - gem update bundler
bundler_args: --without development
language: ruby
env:
  global:
    - CODECLIMATE_REPO_TOKEN=1fa179913fd57a6d2aab7013a56a224c3837561da507f5cff8f10e13c425d289
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - rbx-2
  - ruby-head
matrix:
  include:
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
script: bundle exec rake
